apiVersion : v1
kind: Service
metadata:
  name: jenkins
  labels:
      app: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
    tier: cicd
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
      tier: cicd
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        tier: cicd
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
              name: jenkins
